### ISSUE TITLE
virtualenv issues

### ISSUE THREAD

**Issue by jdx** [jdxcode/asdf-python#4]
see https://github.com/jdxcode/rtx/issues/8#issuecomment-1454960928 for context

- [ ] virtualenv not deactivating when navigating away
- [x] virtualenv created in subdirectory, not project root
- [x] ability to use absolute paths with environment variables like `$HOME/.venv`

@delicb I wasn't able to reproduce the first one here. If you can manage to make it happen again, it would be helpful if I could see the output of `echo $__RTX_DIFF` (which I can decode the base64 of to make useful, no need to do that for me).

If you can also dive a bit further, you could add `set -x` to `~/.local/share/rtx/plugins/python/bin/exec-env` to see what it's doing and when it is running. Also make sure you've updated both rtx and rtx-python since I've made several changes to both today.

**Comment by jdx** [comment]
here's me testing it:

```
~ ❯ cd ~/src/rtx-python/
rtx-python  main ❯ echo $VIRTUAL_ENV
/Users/jdx/.config/rtx/.venv
rtx-python  main ❯ cd ~
~ ❯ echo $VIRTUAL_ENV

~ ❯ cd ~/src/rtx-python/test
rtx-python/test  main ❯ echo $VIRTUAL_ENV
/Users/jdx/.config/rtx/.venv
rtx-python/test  main ❯ cd
~ ❯ echo $VIRTUAL_ENV

~ ❯ cd ~/src/rtx-python/test
rtx-python/test  main ❯ cd ..
rtx-python  main ❯ echo $VIRTUAL_ENV
/Users/jdx/.config/rtx/.venv
rtx-python  main ❯ cd ~
~ ❯ echo $VIRTUAL_ENV
```

it doesn't seem to "stick". Of course I believe you that this did happen, just not sure how to trigger it.

I suspect it might be related to something like changing directories multiple times, editing the `.rtx.toml`, or something like that but nothing I found would trigger it so far.

**Comment by delicb** [comment]
@jdxcode With latest version of `rtx` and this plugin I can no longer reproduce "stickiness". I have reproduced it earlier is fresh docker container and just tried it now as well, but it seems to be working now. I will try more directly on my laptop couple more times, but for now it seems to be resolved.
